### ISSUE TITLE
experiment: showing our community page on errors

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber-engine#22]
We want to incentivize our users to talk to us when they encounter problems by showing them our link to Slack in the exception message.

In ploomber-core 0.1, I added some custom exceptions, so we do that. Essentially, we want to replace some errors with their customized counterparts:

`ValueError` -> `PloomberValueError`
`TypeError` -> `PloomberTypeError`

see [documentation here](https://ploomber-core.readthedocs.io/en/latest/exceptions.html)

**Comment by idomic** [comment]
This description is a bit off, we have a [sample](https://github.com/ploomber/sklearn-evaluation/blob/f887dcf1105fd7fe0f252aaaff44bc8c2991d11b/tests/test_plot_bad_input.py) in SKE, where we override and maintain the existing built-in error types.

**Comment by tonykploomber** [comment]
I scanned the codebase and realized that we don't have any place raises `ValueError` or `TypeError`.

Probably I am missing, @edublancas  can you verify my statement is true?

**Comment by edublancas** [comment]
you're right @tonykploomber, I'll close this
