### ISSUE TITLE
Telemetry for errors

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber-engine#23]
We currently don't track errors on the package.

**Comment by edublancas** [comment]
are you sure?

we're using [log_call](https://github.com/ploomber/ploomber-engine/blob/5e8a44df3500a3b8b0809e7b86088226d3288a49/src/ploomber_engine/engine.py#L19), which [logs errors](https://github.com/ploomber/core/blob/main/src/ploomber_core/telemetry/telemetry.py#L545)

**Comment by idomic** [comment]
I saw that, but I couldn't find events and I'd be surprised if it has 0 errors, I'll try breaking it and checking for events.

**Comment by edublancas** [comment]
I reproduced this. moving it to ploomber-core https://github.com/ploomber/core/issues/35
