### ISSUE TITLE
proposal: pytest plugin

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber-engine#26]
this package is [pretty cool](https://github.com/computationalmodelling/nbval), but development isn't very active. it implements a pytest plugin so you can test notebooks with:

```sh
pytest --nbval
```

We could implement a basic version since we already have some [notebook testing capabilities](https://github.com/ploomber/ploomber-engine/blob/931fc187d0628912334a0b48de13014600f532de/src/ploomber_engine/testing.py#L52).

**Comment by idomic** [comment]
Interesting, how does it happen in CIs today? Custom scripts with papermill/engine?

**Comment by edublancas** [comment]
yeah, I've seen many projects just call papermill as part of their CI while others use nbval or similar
