### ISSUE TITLE
add cwd to execute_notebook (kwarg exists in papermill) 

### ISSUE THREAD

**Issue by avivajpeyi** [ploomber/ploomber-engine#53]
`cwd` allows the user to set the path to execute a notebook. This feature is present as a kwarg in papermill: 
https://github.com/nteract/papermill/blob/54f6c038cdae0c70d5fb04691fa465e12aeb62cb/papermill/execute.py#L29

**Comment by edublancas** [comment]
awesome, I see you started working on it! request my review once you want me to take a look. and feel free to ask any questions along the way
