### ISSUE TITLE
execute_notebook `cwd` not working as expected

### ISSUE THREAD

**Issue by avivajpeyi** [ploomber/ploomber-engine#57]
i think the cwd is not working outside the pytest env :sweat_smile: 

For example, consider the following: 

```tree
.
├── run_execute_notebook.py
└── some_dir
    └── test.ipynb
```

**run_execute_notebook.py**
```python
from ploomber_engine import execute_notebook

DIR = ".some_dir"
IPYNB = DIR + "/test.ipynb"
execute_notebook(IPYNB, IPYNB, cwd=DIR)
```

**some_dir/test.ipynb**
```python
#%%
import os
os.getcwd()
#%%
! touch test_file.txt
#%%
import matplotlib.pyplot as plt
plt.figure().savefig('test.png')
```

Running:
`python run_execute_notebook.py`, the files are not stored in the `some_dir` but the top dir where python is run...
```tree
.
├── run_execute_notebook.py
├── some_dir
│   └── test.ipynb
├── test.png
└── test_file.txt
```

[test_cwd.zip](https://github.com/ploomber/ploomber-engine/files/10893612/test_cwd.zip)

**Comment by edublancas** [comment]
thanks for the fix, I'll make a release once the CI passes in master!
