### ISSUE TITLE
ploomber-engine cli isn't well documented

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber-engine#60]
The only place in the docs it's mentioned a user can run via cli is the API spec and it's also via python.

We should add the commands descriptions into docs, including scheduling notebooks via terminal:
`ploomber-engine to_run.ipynb output.ipynb`

(Basically document everything that `ploomber-engine --help shows`)

**Comment by edublancas** [comment]
In the running notebooks docs we have a drop-down to show the CLI equivalent:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/989250/224553988-15aaaa89-9db1-412b-a4f5-d5da39a5448c.png">

do you think we should change how we show this?


I agree that the CLI API docs are missing, we should add a section in the API reference
