### ISSUE TITLE
engine and papermill differences

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber-engine#61]
When running the same notebook with `--log-output` `papermill` shows all of the outputs and `ploomber-engine` doesn't.

This happens on our posthog reporting notebook.
For instance Cell 26, shows the output in papermill:
<img width="773" alt="Screen Shot 2023-03-12 at 10 24 41 AM" src="https://user-images.githubusercontent.com/11596985/224551022-1a069fe9-8b05-4abe-ac2a-3b10dd048cfd.png">

But Doesn't in ploomber-engine:
<img width="1421" alt="Screen Shot 2023-03-12 at 10 24 26 AM" src="https://user-images.githubusercontent.com/11596985/224551042-75249701-c543-4255-a16a-43fc520b01b2.png">

Another thing I noticed is when the notebook runs, there's a dual progress bar within the cell the messes with the main bar, that might be confusing for users. (in `ploomber-engine`)

**Comment by edublancas** [comment]
I ran two sample notebooks ([sample-notebooks.zip](https://github.com/ploomber/ploomber-engine/files/10951495/sample-notebooks.zip)) to understand the issue a bit more, some comments:

## printed output

I was unable to reproduce the issue, all print statements are displayed when passing `--log-output`; ploomber-engine only displays whatever is sent to `stdout` so my guess is that papermill is also displaying `stderr` and/or the text results from each cell - we should run a more detailed analysis and then ensure that both produce the same output. Another thing we can add is the cell delimiter (papermill prints: `Executing Cell X -----`)

```
ploomber-engine print.ipynb /dev/null --log-output
```

## dual progress bar

I could not reproduce this by creating notebook that displays a progressbar using tqdm and executing it with `--log-output`, so we need to investigate more:

```
ploomber-engine progress.ipynb /dev/null --log-output
```

**Comment by mehtamohit013** [comment]
Hi @idomic 
Can you please provide me with posthob.ipynb or where it is located?
I can't seem to find it.

**Comment by edublancas** [comment]
I think the missing output might be that the tqdm progress bar is printed to standard error and we're just displaying standard output. If that's the case, we should ensure we also display standard error in the console.

You can check this with:

```python
import sys

print("printing to stderr", file=sys.stderr)
```

and see if ploomber-engine displays it

**Comment by mehtamohit013** [comment]
Some clarification regarding performance

- I have extracted 15 samples from profiling with a mean of 1.02846 sec and std dev of 0.0047 sec
- I have used the `time` command of zsh, and I am getting time in the range of 1.15 - 1.22 sec
- The 5-8 sec that I mentioned above is the time, the zsh shell is taking to generate a new command for me to input. So maybe it should include the delay in stdout displaying to the shell.

Just a minor observation: We cannot pass the file name to which data should be saved in ` --save-profiling-data`. It creates `output-profiling-data.csv` by default

**Comment by mehtamohit013** [comment]
> I think the missing output might be that the tqdm progress bar is printed to standard error and we're just displaying standard output. If that's the case, we should ensure we also display standard error in the console.

Hi @edublancas ,
Currently, ploomber engine prints the output from stdout only when the cell is completely executed, however, this is not ideal as the output should be printed to the console as soon as it is printed to notebook stdout

I have mentioned more details in PR #66
