### ISSUE TITLE
ploomber-engine displaying standard error even without `--log-output`

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber-engine#71]
I was testing the feature introduced in https://github.com/ploomber/ploomber-engine/pull/66 and realized that standard error is displayed even when missing the `--log-output` argument, is this expected?

![image](https://user-images.githubusercontent.com/989250/226481953-359767a4-f95f-4a7a-b33e-07bc1f9efb72.png)

also, I saw that the progress bars are correctly displayed now but the changelog does not mention anything, is there anything missing here?

cc @mehtamohit013

**Comment by mehtamohit013** [comment]
> I was testing the feature introduced in #66 and realized that standard error is displayed even when missing the `--log-output` argument, is this expected?

 Yes, `stderr` is always displayed. `--log-output` is for `stdout` 

> also, I saw that the progress bars are correctly displayed now but the changelog does not mention anything, is there anything missing here?

Because you are not printing something in `for` loop. If you are not printing, everything works fine

Try this:
```python
for i in tqdm(range(10)):
    time.sleep(0.1)
    if i%2==0:
        print(i)
```

**Comment by mehtamohit013** [comment]
In changelog I mentioned: "* [Fix] Temporary Fixed `stdout` and `stderr` stream. Ploomber Engine now flush both `stdout` and `stderr` as soon as it got from the notebook"

**Comment by edublancas** [comment]
ok cool, we can close this then
