### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber-engine#8]
we need to create documentation for this project using [jupyter-book](https://github.com/executablebooks/jupyter-book). for an example with full setup, [see this](https://github.com/ploomber/jupysql). once the skeleton is done, I can configure it, so it deploys using readthedocs.org

- [ ] create skeleton using jupyter-book
- [ ] add readthedocs configuration
- [ ] deploy to readthedocs (I can do this)
- [ ] add notebook with [debuglater](https://github.com/ploomber/ploomber-engine#debug-later) tutorial
- [ ] add [debug now](https://github.com/ploomber/ploomber-engine#debug-now) tutorial
- [ ] add [notebook profiling](https://github.com/ploomber/ploomber-engine#notebook-profiling-cpu-gpu-ram) tutorial

Note: the tutorials will be a series of commands (not Python code). we can use the `%%bash` magic to execute bash inside a Jupyter notebook; however, we started experimenting with the [bash kernel](https://github.com/takluyver/bash_kernel); let's see if that works here

**Comment by RodolfoFerro** [comment]
Done so far:
- [x] create skeleton using jupyter-book
- [ ] add readthedocs configuration
- [ ] deploy to readthedocs (I can do this)
- [x] add notebook with [debuglater](https://github.com/ploomber/ploomber-engine#debug-later) tutorial
- [x] add [debug now](https://github.com/ploomber/ploomber-engine#debug-now) tutorial
- [x] add [notebook profiling](https://github.com/ploomber/ploomber-engine#notebook-profiling-cpu-gpu-ram) tutorial

**Comment by edublancas** [comment]
the readthedocs is failing, please fix it: https://readthedocs.org/projects/ploomber-engine/builds/18082700/

you can deploy from a development branch and once that's passing, open a PR

**Comment by edublancas** [comment]
merged! looks like the readthedocs config was changed to serve from dev? do you need to change anything so it serves from main?

**Comment by RodolfoFerro** [comment]
> merged! looks like the readthedocs config was changed to serve from dev? do you need to change anything so it serves from main?

Yes, but now it's done! It is being served from the main branch:
https://readthedocs.org/projects/ploomber-engine/builds/18184543/

**Comment by edublancas** [comment]
closing this now!
