### ISSUE TITLE
Inspection and type of parameters

### ISSUE THREAD

**Issue by vijayvammi** [ploomber/ploomber-engine#87]
Hello Eduardo,

Thanks for the ploomber engine. I integrated it in my projects and it works well.

Is there a way to inspect a notebook to get the parameters needed by the notebook and also their types?
If that is possible, it would be nicer to get the schema definition if they are richer types like dataclasses or pydantic models.

Cheers,
Vijay

**Comment by edublancas** [comment]
hi @vijayvammi,

There's currently no way to do this; I remember seeing something like this in papermill's codebase, so if you have time, we could port the code over here!

Should be pretty straightforward (just remember to add the license at the top of the file)

let me know if you're interested!
